// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// straw_R
RcppExport SEXP straw_R(String argv);
RcppExport SEXP _BentoBox_straw_R(SEXP argvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type argv(argvSEXP);
    rcpp_result_gen = Rcpp::wrap(straw_R(argv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BentoBox_straw_R", (DL_FUNC) &_BentoBox_straw_R, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BentoBox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
