// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// checkRow
NumericMatrix checkRow(NumericMatrix x, int maxRows, int rowCol, double wiggle);
RcppExport SEXP _BentoBox_checkRow(SEXP xSEXP, SEXP maxRowsSEXP, SEXP rowColSEXP, SEXP wiggleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxRows(maxRowsSEXP);
    Rcpp::traits::input_parameter< int >::type rowCol(rowColSEXP);
    Rcpp::traits::input_parameter< double >::type wiggle(wiggleSEXP);
    rcpp_result_gen = Rcpp::wrap(checkRow(x, maxRows, rowCol, wiggle));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BentoBox_checkRow", (DL_FUNC) &_BentoBox_checkRow, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BentoBox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
